export const french = {
  interest: "Centres d'intérets",
  music: "Musique",
  modeling: "Modélisation",
  games: "Jeux Vidéos",
  projects: "Mes projets",
  arcade: "Borne d'arcade",
  intro: "Bienvenue !",
  intro2: "Je m'appelle Nathan LEMALE, je suis un développeur français de 19 ans !",
  intro3: "Je suis acctuellement en troisième année d'étude à Epitech Bordeaux avec un GPA de 3.26 / 4.",
  intro4: "Sur cette application vous pouvez retrouver différents projets que j'ai réalisé !",
  intro5: "Vous avez également une page comprenant certains de mes centres d'intérets.",
  intro6: "Pour toute question supplémentaire, consultez ma page contacts !",
  contact: "Contacts",
  phone: "Téléphone",
  address: "Adresse",
  settings: "Paramètres",
  language: "Choisissez la langue:",
  theme: "Choisissez le thème:",
};

export const english = {
  interest: "Interests",
  music: "Musique",
  modeling: "Modélisation",
  games: "Jeux Vidéos",
  projects: "Mes projets",
  arcade: "Borne d'arcade",
  intro: "Bienvenue !",
  intro2: "Je m'appelle Nathan LEMALE, je suis un développeur français de 19 ans !",
  intro3: "Je suis acctuellement en troisième année d'étude à Epitech Bordeaux avec un GPA de 3.26 / 4.",
  intro4: "Sur cette application vous pouvez retrouver différents projets que j'ai réalisé !",
  intro5: "Vous avez également une page comprenant certains de mes centres d'intérets.",
  intro6: "Pour toute question supplémentaire, consultez ma page contacts !",
  contact: "Contacts",
  phone: "Téléphone",
  address: "Adresse",
  settings: "Paramètres",
  language: "Choisissez la langue:",
  theme: "Choisissez le thème:",
};

