export const french = {
  interest: "Centres d'intérets",
  music: "Musique",
  modeling: "Modélisation",
  games: "Jeux Vidéos",
  projects: "Mes projets",
  bomberman: "Bomberman",
  arcade: "Borne d'arcade",
  defender: "Tower Defense",
  plazza: "Plazza",
  rpg: "RPG",
  intro: "Bienvenue !",
  me: "Je m'appelle Nathan LEMALE, je suis un développeur français de 19 ans !",
  epitech: "Je suis acctuellement en troisième année d'étude à Epitech Bordeaux avec un GPA de 3.26 / 4.",
  myProjects: "Sur cette application vous pouvez retrouver différents projets que j'ai réalisé !",
  myInterests: "Vous avez également une page comprenant certains de mes centres d'intérets.",
  myContacts: "Pour toute question supplémentaire, consultez ma page contacts !",
  contact: "Contacts",
  age: "19 ans",
  phone: "Téléphone",
  address: "Adresse",
  settings: "Paramètres",
  language: "Choisissez la langue:",
  theme: "Choisissez le thème:",
};

export const english = {
  interest: "Interests",
  music: "Music",
  modeling: "Modeling",
  games: "Videos Games",
  projects: "Projects",
  bomberman: "Bomberman",
  arcade: "Arcade game",
  defender: "Tower Defense",
  plazza: "Plazza",
  rpg: "RPG",
  intro: "Hello There !",
  me: "I'm Nathan Lemale, a french 19 years french developer !",
  epitech: "Currently in third year at Epitech Bordeaux, I have a GPA of 3.28 / 4.",
  myProjects: "On this app you will find some projects I did !",
  myInterests: "Some of my interests can be found on my Interest page.",
  myContacts: "If you have any other question or if you want to contact me you, check my contact page !",
  contact: "Contacts",
  age: "19 yo",
  phone: "Phone",
  address: "Adress",
  settings: "Settings",
  language: "Choose your language:",
  theme: "Choose your theme:",
};

